font:
  normal:
    family: "Red Hat Mono"
    style: Medium

  bold:
    family: "Red Hat Mono"
    style: Bold

  italic:
    family: "Red Hat Mono"
    style: Medium Italic

  bold_italic:
    family: "Red Hat Mono"
    style: Bold Italic

  size: 10

window:
  padding:
    x: 0
    y: 0
  dynamic_title: true

colors:
  primary:
    background: '#1c1c1c'
    foreground: '#d7d7af'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: '#d7d7af'
    background: '#875f5f'
  search:
    matches:
      foreground: CellBackground
      background: '#878787'
    bar:
      background: '#af5f5f'
      foreground: '#121212'
  normal:
    black: '#1c1c1c' #edited
    red: '#875f5f' #edited
    green: '#a3be8c'
    yellow: '#87875f' #edited
    blue: '#87afaf' #edited
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#262626' #edited
    red: '#af5f5f' #edited
    green: '#a3be8c'
    yellow: '#af875f' #edited
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'
