font:
  normal:
    family: "Red Hat Mono"
    style: Medium

  bold:
    family: "Red Hat Mono"
    style: Bold

  italic:
    family: "Red Hat Mono"
    style: Medium Italic

  bold_italic:
    family: "Red Hat Mono"
    style: Bold Italic

  size: 12

window:
  padding:
    x: 0
    y: 0
  dynamic_title: true

colors:
  primary:
    background: '#1c1c1c'
    foreground: '#d7d7af'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: '#d7d7af'
    background: '#875f5f'
  search:
    matches:
      foreground: CellBackground
      background: '#878787'
    bar:
      background: '#af5f5f'
      foreground: '#121212'
  normal:
    black: '#1c1c1c' #edited
    red: '#af5f5f' #edited
    green: '#af875f' #edited
    yellow: '#87875f' #edited
    blue: '#ae5f00' #edited
    magenta: '#878787' #edited
    cyan: '#875f5f' #edited
    white: '#d8dee9' #edited
  bright:
    black: '#262626' #edited
    red: '#af5f5f' #edited
    green: '#af875f' #edited
    yellow: '#ffd787' #edited
    blue: '#ae5f00'
    magenta: '#878787' #edited
    cyan: '#875f5f' # edited
    white: '#d8dee9' #edited
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#d8dee9'
      # bruh broh
      # ???
