#!/bin/sh

echo "What video driver do you want to use? (https://wiki.archlinux.org/title/Xorg#Driver_installation)"
echo "Supported video drivers:"
echo "xf86-video-amdgpu (amd)"
echo "xf86-video-ati (amd-ati)"
echo "xf86-video-intel (intel)"
echo "xf86-video-nouveau (nvidia)"
echo "xf86-video-fbdev (virtualbox)"
read VIDEO_DRIVER

echo "Installing required packages"
# split package installations incase it's unable to find one of them
sudo pacman -S base-devel --noconfirm
sudo pacman -S $VIDEO_DRIVER --noconfirm
sudo pacman -S xorg xorg-xinit --noconfirm
sudo pacman -S awesome mesa --noconfirm
sudo pacman -S ttf-fira-code --noconfirm

echo "Building simple terminal"
mkdir build && cd build
echo "Cloning st"
git clone https://git.suckless.org/st && cd st
echo "Replacing config"
wget https://raw.githubusercontent.com/camper0008/arch/stable/install/config/st-config.h
rm config.h
mv st-config.h config.h
sudo make clean install
cd ..

echo "Creating configuration files"
cp /etc/X11/xinit/xinitrc ~/.xinitrc
mkdir -p ~/.config/awesome/
cp /etc/xdg/awesome/rc.lua ~/.config/awesome/

echo "Installing awesome theme"
cd /usr/share/awesome/themes
git clone https://github.com/hmix/awesome-wm-nord-theme.git nord

echo "Editing awesome theme"
cd
awk '{ gsub(/default\/theme\.lua/, "nord/theme.lua"); print }' ~/.config/awesome/rc.lua > /tmp/rc.lua.tmp
cat /tmp/rc.lua.tmp > ~/rc.lua

echo "Editing awesome default terminal"
awk '{ gsub(/terminal = "xterm"/, "terminal = \"st\""); print }' ~/.config/awesome/rc.lua > /tmp/rc.lua.tmp
cat /tmp/rc.lua.tmp > ~/rc.lua

echo "Editing awesome default editor"
awk '{ gsub(/editor = os.getenv\("EDITOR"\) or "nano"/, "editor = os.getenv\(\"EDITOR\"\) or \"vim\""); print }' ~/.config/awesome/rc.lua > /tmp/rc.lua.tmp
cat /tmp/rc.lua.tmp > ~/rc.lua

echo "Configuring"
awk '{ gsub(/^((twm)|(xclock)|(xterm)|(exec xterm)).*/, ""); print }' ~/.xinitrc > /tmp/.xinitrc.tmp
echo "setxkbmap -layout dk" >> /tmp/.xinitrc.tmp
echo "exec awesome" >> /tmp/.xinitrc.tmp
cat /tmp/.xinitrc.tmp > ~/.xinitrc
echo ""
echo "Installation finished. Execute 'startx' to run."
